/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(packet_filter.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(64fd88703dbc1e83f0e5fc3275baafbd)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/hsdec/packet_filter.h>
// pydoc.h is automatically generated in the build directory
#include <packet_filter_pydoc.h>

void bind_packet_filter(py::module& m)
{

    using packet_filter    = ::gr::hsdec::packet_filter;


    py::class_<packet_filter, gr::block, gr::basic_block,
        std::shared_ptr<packet_filter>>(m, "packet_filter", D(packet_filter))

        .def(py::init(&packet_filter::make),
           py::arg("chunk_len"),
           py::arg("sps"),
           D(packet_filter,make)
        )
        



        ;




}








