/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(qpsk_frame_sync.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(140fe12476b2db9afe9d6f280dc780a8)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/hsdec/qpsk_frame_sync.h>
// pydoc.h is automatically generated in the build directory
#include <qpsk_frame_sync_pydoc.h>

void bind_qpsk_frame_sync(py::module& m)
{

    using qpsk_frame_sync    = ::gr::hsdec::qpsk_frame_sync;


    py::class_<qpsk_frame_sync, gr::block, gr::basic_block,
        std::shared_ptr<qpsk_frame_sync>>(m, "qpsk_frame_sync", D(qpsk_frame_sync))

        .def(py::init(&qpsk_frame_sync::make),
           py::arg("code"),
           py::arg("len"),
           py::arg("block_size"),
           D(qpsk_frame_sync,make)
        )
        



        ;




}








