/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(qpsk_packet_filter.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(46ee5dee7f2d765c01b7d3fefa7ac7d5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/hsdec/qpsk_packet_filter.h>
// pydoc.h is automatically generated in the build directory
#include <qpsk_packet_filter_pydoc.h>

void bind_qpsk_packet_filter(py::module& m)
{

    using qpsk_packet_filter    = ::gr::hsdec::qpsk_packet_filter;


    py::class_<qpsk_packet_filter, gr::block, gr::basic_block,
        std::shared_ptr<qpsk_packet_filter>>(m, "qpsk_packet_filter", D(qpsk_packet_filter))

        .def(py::init(&qpsk_packet_filter::make),
           py::arg("chunk_len"),
           py::arg("sps"),
           D(qpsk_packet_filter,make)
        )
        



        ;




}








