/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(rs_4.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1bdbf34df1736db0d1ce0419d7ac415b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/hsdec/rs_4.h>
// pydoc.h is automatically generated in the build directory
#include <rs_4_pydoc.h>

void bind_rs_4(py::module& m)
{

    using rs_4    = gr::hsdec::rs_4;


    py::class_<rs_4, gr::block, gr::basic_block,
        std::shared_ptr<rs_4>>(m, "rs_4", D(rs_4))

        .def(py::init(&rs_4::make),
           D(rs_4,make)
        )
        



        ;




}








