/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(send_pack.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5e52c39f5a7fac476e9bf39e864a579c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/hsdec/send_pack.h>
// pydoc.h is automatically generated in the build directory
#include <send_pack_pydoc.h>

void bind_send_pack(py::module& m)
{

    using send_pack    = ::gr::hsdec::send_pack;


    py::class_<send_pack, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<send_pack>>(m, "send_pack", D(send_pack))

        .def(py::init(&send_pack::make),
           py::arg("scra"),
           py::arg("empty"),
           D(send_pack,make)
        )
        



        ;




}








