/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(squelch_new.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c5fff19dcb4ce7691899ad39e1adcdf4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/hsdec/squelch_new.h>
// pydoc.h is automatically generated in the build directory
#include <squelch_new_pydoc.h>

void bind_squelch_new(py::module& m)
{

    using squelch_new    = ::gr::hsdec::squelch_new;


    py::class_<squelch_new, gr::block, gr::basic_block,
        std::shared_ptr<squelch_new>>(m, "squelch_new", D(squelch_new))

        .def(py::init(&squelch_new::make),
           py::arg("arg0"),
           D(squelch_new,make)
        )
        



        ;




}








