/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(tail.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8b746b7bf55ce2f9cc5543afcb0e6cc1)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/hsdec/tail.h>
// pydoc.h is automatically generated in the build directory
#include <tail_pydoc.h>

void bind_tail(py::module& m)
{

    using tail    = ::gr::hsdec::tail;


    py::class_<tail, gr::block, gr::basic_block,
        std::shared_ptr<tail>>(m, "tail", D(tail))

        .def(py::init(&tail::make),
           py::arg("n"),
           py::arg("m"),
           D(tail,make)
        )
        



        ;




}








