/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(variable_pack_enc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(99296d541c643db4c5605da1a0184cef)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/hsdec/variable_pack_enc.h>
// pydoc.h is automatically generated in the build directory
#include <variable_pack_enc_pydoc.h>

void bind_variable_pack_enc(py::module& m)
{

    using variable_pack_enc    = ::gr::hsdec::variable_pack_enc;


    py::class_<variable_pack_enc, gr::block, gr::basic_block,
        std::shared_ptr<variable_pack_enc>>(m, "variable_pack_enc", D(variable_pack_enc))

        .def(py::init(&variable_pack_enc::make),
           py::arg("call"),
           py::arg("preamble_len"),
           D(variable_pack_enc,make)
        )
        



        ;




}








